M by tenlevels - Added NDS selected and unselected icons
OnionUI/Themes pull request #23
Opened 2024-01-11 02:11 UTC by thana-than

Followed the existing style by reducing output white level from 255 to 100 then desaturating.

2024-01-17 21:28 UTC, Aemiii91 commented
Hi, to trigger a re-release, you'll need to delete the zip file in the release folder

2024-01-17 21:29 UTC, Aemiii91 requested changes
Hi, to trigger a re-release, you'll need to delete the zip file in the release folder

2024-01-21 06:03 UTC, thana-than commented
Hi, I removed the zip for the theme from the releases folder. Is that what you wanted? Please let me know if I'm missing something. Thanks!

2024-01-21 06:48 UTC, Aemiii91 approved these changes

2024-01-21 06:48 UTC, merged